### ISSUE TITLE
Pulling ACPL data from games

### ISSUE THREAD

**Issue by sharmaabhishekk** [cyanfish/python-lichess#10]
Hi 👋, thank you for this excellent library. I have only recently started using it but I'm loving it. 

I was wondering if there could be any way to pull the average centipawn loss for each game into the PGN of the games (`lichess.api.user_games`).  Currently I have to use stockfish to do it externally but if I could get the lichess calculated centipawn loss in the PGN that would be great!

**Comment by charlesoblack** [comment]
I'm pretty sure you can do it for games that have been analyzed by Lichess already. If you call `lichess.api.user_games(..., evals='true')` you'll get the evaluations as PGN comments that you can then extract using e.g. `python-chess` (or you could roll your own), and then calculate the average CPL from that.

I don't think Lichess provides the actual CPL between moves through the API, just the evals.

**Comment by charlesoblack** [comment]
Here's an example of how to do it with a `python-chess` Visitor: https://github.com/charlesoblack/chess-pipeline/blob/a516a1c19c6f96dd92cfd5c1562c5963c1778f73/src/pipeline_import/visitors.py#L10

**Comment by sharmaabhishekk** [comment]
Thanks @charlesoblack, that does the trick!
