### ISSUE TITLE
"Lichess is down" error

### ISSUE THREAD

**Issue by charlesoblack** [cyanfish/python-lichess#11]
Sometimes when Lichess is down, any API requests get a 502 HTTP response and some text along the lines of, `We expect to be back very soon. Thanks for your patience`. Should this be an error caught by `python-lichess`? I think if a 502 error is returned then the library could probably wait ~20-30s and re-request the same thing and it would work.

**Comment by cyanfish** [comment]
PR merged and published in 0.10.

**Comment by guidopetri** [comment]
Shoot, thank you! I hope I didn't bother you with that ping on the Lichess discord.

**Comment by cyanfish** [comment]
Nah it's fine, just been super busy lately
