### ISSUE TITLE
Games by User link still not working?

### ISSUE THREAD

**Issue by charlesoblack** [cyanfish/python-lichess#4]
Related to #2 . Seems like installing from PyPi still has the incorrect link in the `/api/__init__.py` file. I'm not sure how to fix this exactly.

**Comment by cyanfish** [comment]
Should be fixed now (in version 0.9). The PyPi docs don't mention that you have to manually clean out old build files before rebuilding the package, so some files from old versions were still there.

**Comment by charlesoblack** [comment]
Thanks cyanfish!
